export const ENV = {
    LIVEKIT_PUBLIC_KEY: import.meta.env.VITE_LIVEKIT_PUBLIC_KEY,
    LIVEKIT_SECRET_KEY: import.meta.env.VITE_LIVEKIT_SECRET_KEY,
    LIVEKIT_SERVER_URL: import.meta.env.VITE_LIVEKIT_SERVER_URL
}